---
descriptor_extension: yml
version: '0.5'
package:
  vendor: "eu.5gtango"
  name: "generic-probes-test-pingonly-single-td-multiple-ns"
  version: "0.1"
  maintainer: "Santiago Rodríguez, OPTARE"
  description: "This is a 5GTANGO test package for test probes"
files:
  - path: "Definitions/test-descriptor.yml"
    type: "application/vnd.5gtango.tstd"
    testing_tags:
      - "td-tt-matches-multiple-ns-tt"
  - path: "Icons/optare_solutions.png"
    type: "image/png"
  - path: "Licenses/LICENSE"
    type: "text/plain"
