---
descriptor_extension: yml
version: '0.5'
package:
  vendor: "eu.5gtango"
  name: "media-hls-test"
  version: "0.1"
  maintainer: "Felipe Vicens, ATOS"
  description: "This is a 5GTANGO test package to check the stability of the HLS playlists"
files:
  - path: "Definitions/test-descriptor.yml"
    type: "application/vnd.5gtango.tstd"
    testing_tags:
      - "hls-media-service"
  - path: "Icons/upb_logo.png"
    type: "image/png"
  - path: "Licenses/LICENSE"
    type: "text/plain"
