---
descriptor_extension: yml
version: '0.5'
package:
  vendor: "eu.5gtango"
  name: "comm-pilot-test-headless-browser"
  version: "0.1"
  maintainer: "Santiago Rodríguez, OPTARE"
  description: "This is a 5GTANGO test package for test probes"
files:
  - path: "Definitions/test-descriptor.yml"
    type: "application/vnd.5gtango.tstd"
    testing_tags:
      - "comm-pilot-test"
  - path: "Licenses/LICENSE"
    type: "text/plain"
