---
descriptor_extension: yml
version: '0.5'
package:
  vendor: "eu.5gtango"
  name: "telnet-osm-cloud-init-test"
  version: "0.1"
  maintainer: "Ignacio Dominguez (Atos)"
  description: "Package with telnet probe to test cloud-init in OSM"
files:
  - path: "Definitions/test-descriptor.yml"
    type: "application/vnd.5gtango.tstd"
    testing_tags:
      - "osm-cloud-init-test"
  - path: "Icons/atos_logo.png"
    type: "image/png"
  - path: "Licenses/LICENSE"
    type: "text/plain"
