---
descriptor_extension: yml
version: '0.5'
package:
  vendor: "eu.5gtango"
  name: "ns-nsid1v-1-td-tt-n-ns-tt-2"
  version: "0.2"
  maintainer: "5GTANGO Test Team"
  description: "This is a integration test artifact."
files:
  - path: "nsd.yaml"
    type: "application/vnd.5gtango.nsd"
    tags:  # (optional)
      - "eu.5gtango"
    testing_tags:
      - "td-tt-matches-multiple-ns-tt"
  - path: "vnfd1.yaml"
    type: "application/vnd.5gtango.vnfd"
    tags:  # (optional)
      - "eu.5gtango"
