---
descriptor_extension: yml
version: '0.5'
package:
  vendor: "eu.5gtango"
  name: "test-ns-nsid1v-sonata"
  version: "0.2"
  maintainer: "5GTANGO Test Team"
  description: "This is a integration test artifact."
files:
  - path: "nsd.yaml"
    type: "application/vnd.5gtango.nsd"
    tags:  # (optional)
      - "eu.5gtango"
    testing_tags:
      - "eu.5gtango.sonata"
  - path: "vnfd1.yaml"
    type: "application/vnd.5gtango.vnfd"
    tags:  # (optional)
      - "eu.5gtango"
